#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Next.js reads local dev config from .env.local (gitignored via .env*).
ENV_FILE=".env.local"

# vercel_env_push NAME VALUE TARGET [--sensitive] — upsert one Vercel env var.
# `vercel env add` fails if the var already exists in that target, so remove
# it first; the removal error on a first run is expected and swallowed.
vercel_env_push() {
  local name="$1" value="$2" target="$3" sensitive="${4:-}"
  npx vercel env rm "$name" "$target" --yes >/dev/null 2>&1 || true
  # shellcheck disable=SC2086  # $sensitive is an optional flag, not data
  if printf '%s' "$value" | npx vercel env add "$name" "$target" $sensitive >/dev/null 2>&1; then
    printf '  %s✓ pushed%s %s → Vercel (%s)\n' "$GREEN" "$RESET" "$name" "$target"
  else
    SKIPPED+=("Vercel env $name ($target) — add it in Project Settings → Environment Variables")
    warn "couldn't push $name to Vercel ($target)"
  fi
}

banner "Wild Coast Kids — secrets setup (Supabase, R2, Vercel)"

# ── Stage 1: Supabase public config ───────────────────────────────────────
stage "Supabase — project URL and publishable key"
say "These two are browser-safe by design; Row Level Security is what protects data."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Pick your project if prompted. On API Settings, copy the Project URL"
step "(https://<ref>.supabase.co). If the page only shows keys, the URL is"
step "under Project Settings → Data API."
ask NEXT_PUBLIC_SUPABASE_URL "Paste the project URL:"
step "Copy the publishable key (sb_publishable_...) — on older dashboards this"
step "is the 'anon / public' key under Project API keys."
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the publishable/anon key:"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"

# ── Stage 2: Supabase secret key ──────────────────────────────────────────
stage "Supabase — service-role (secret) key"
say "Server-only: it bypasses Row Level Security. It never gets a NEXT_PUBLIC_"
say "prefix and must only be read in route handlers / server actions."
step "On the same API settings page, reveal and copy the secret key"
step "(sb_secret_...) — on older dashboards, the 'service_role' key."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the secret key (input hidden):"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── Stage 3: Cloudflare R2 ────────────────────────────────────────────────
stage "Cloudflare R2 — bucket-scoped API token"
say "We'll create a token that can only touch this one bucket, not the account."
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "Click 'Create API token' (create an Account API token if asked to choose)."
step "Permissions: 'Object Read & Write'. Under 'Specify bucket(s)', select"
step "ONLY your site's bucket. Leave TTL as forever, then create the token."
warn "The Secret Access Key is shown once — copy both values before leaving the page."
ask R2_BUCKET_NAME "Bucket name:"
ask R2_ACCESS_KEY_ID "Paste the Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key (input hidden):"
step "Your Account ID is the 32-character hex string in the dashboard URL"
step "(dash.cloudflare.com/<account-id>/...), also shown on the token page's"
step "S3 endpoint: https://<account-id>.r2.cloudflarestorage.com"
ask R2_ACCOUNT_ID "Paste the Account ID:"
write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
write_env R2_BUCKET_NAME "$R2_BUCKET_NAME"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── Stage 4: Link the repo to the Vercel project ──────────────────────────
stage "Vercel — link this repo to your project"
if [[ -f .vercel/project.json ]]; then
  say "Already linked (.vercel/project.json exists) — nothing to do."
else
  say "This runs the Vercel CLI interactively; it will prompt you to log in"
  say "if needed. Answer its questions and pick the existing project."
  note "(npx may ask to install the vercel package — answer y)"
  pause "Press Enter to run 'npx vercel link'..."
  npx vercel link || { warn "linking failed — fix that and re-run the wizard"; exit 1; }
fi

# ── Stage 5: Push the values to Vercel ────────────────────────────────────
stage "Vercel — push environment variables"
say "Public vars go to all three environments; secrets go to production and"
say "preview only (marked sensitive), so local dev stays on .env.local."
if confirm "Push the captured values to Vercel now?"; then
  for target in production preview development; do
    vercel_env_push NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL" "$target"
    vercel_env_push NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY" "$target"
    vercel_env_push R2_ACCOUNT_ID "$R2_ACCOUNT_ID" "$target"
    vercel_env_push R2_BUCKET_NAME "$R2_BUCKET_NAME" "$target"
  done
  for target in production preview; do
    vercel_env_push SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY" "$target" --sensitive
    vercel_env_push R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID" "$target" --sensitive
    vercel_env_push R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY" "$target" --sensitive
  done
else
  SKIPPED+=("Vercel env vars — re-run this wizard or add them in Project Settings → Environment Variables")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
